### ISSUE TITLE
Compliance Git repo not found

### ISSUE THREAD

**Issue by formanojhr** [PopMedNet-Team/Mobile-Application#10]
The repo mentioned for Labkey setup compliance.git not found. 
git clone https://github.com/LabKey/compliance.git

remote: Repository not found.
fatal: repository 'https://github.com/LabKey/compliance.git/' not found

Please advice.

**Comment by zardarkhan** [comment]
The compliance.git is part of a private repository. It is not required however for setting up the servers; see the comment link below for more details:

https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/issues/4#issuecomment-449083692
