### ISSUE TITLE
please write 1 sentence to readme for WCP

### ISSUE THREAD

**Issue by vojtechhuser** [PopMedNet-Team/Mobile-Application#13]
here 
https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/blob/master/FDA-HPHI-StudyDesignerWS-master/README.md

for people who only want to run WCP

**Comment by FDA-MyStudies** [comment]
Hi @vojtechhuser ,

Sorry for the delay in response.  The current ReadMe is no longer empty. 

Thanks!
