### ISSUE TITLE
public instance of WCP

### ISSUE THREAD

**Issue by vojtechhuser** [PopMedNet-Team/Mobile-Application#14]
in the spirit of open source, it would be nice to see a public instance of the WCP for a demo user that can view only forms.

**Comment by FDA-MyStudies** [comment]
@vojtechhuser 

Thank you for the suggestion. Many users have requested this and is public instance of the WCP is being considered. We will update this space when we have any further updates.

**Comment by zwyner** [comment]
@vojtechhuser 

We are currently in the design phase of a demo/public instance of the entire system, including the WCP. We'll post updates in this repository it's publicly available.

Thanks!

**Comment by FDA-MyStudies** [comment]
@vojtechhuser 

We are in the design phase of a public/demo instance of the entire system, including the WCP. We'll post updates to this repository when it is publicly available.
