### ISSUE TITLE
Unable to login to the Study Designer WebApp

### ISSUE THREAD

**Issue by dhanyasathyan** [PopMedNet-Team/Mobile-Application#15]
Hi, I managed:
1.  to get the Study Designer WebApp to build and deployed to tomcat.
2. to get the Study Designer WebService (MetaDataStudy)to build and deploy to tomcat.
3. to get the User Registration WS to build and deploy to Labkey server and inturn to the tomcat. I stuggled with this. will just mention how i did this at the end of my message just to be a good samaritan,

Problems I am stuck with now:
1. i have no idea what to do with the fdaResources folder? how do i build this?
2. I do not know how to login to Study Designer WebApp. The user name and pasasword I picked from the MySQL DB script, doesnt work!

Does any one have any odeas to help me proceed? ANy help / pointers would be much appreciated.

How I got User Registration to build and deploy:(took pointers froma previous post out here).
1. created the build.gradle.
2. fixed the compilation errors in the FdahpUserRegWSManager by using SchemaTableInfo instead of TableInfo.
3. Deleted the plsql folder from the resources\schemas\dbscripts\ folder.
4. Deleted another sql script inside the resources\schemas\dbscripts\sqlserver folder.
5. There are apparently syntax errors on the fdahpuserregws-0.00-1.00.sql which gets executed. Fixed these.
6. Incase you started the tomcat before  even knowing that there are syntax errors, Just delete the tables and the schema created for fdahpUserRegWS in labkey database .
7. ran the gradlew :server:customModules:nameOfYourFolder
8. copied the build from labkey/server/build/modules/nameOfYourFolder to tomcat/webApps
9. started the app from IntelliJ.

**Comment by J0V0** [comment]
Hello @dhanyasathyan I am having the same issue. When I try to login using the default username and password supplied in the documentation, it says "Invalid email or password. Please try again." Did you ever find a solution? Any help would be appreciated. Thanks.

**Comment by dhanyasathyan** [comment]
They were using BCrypt to Hash it. So, the password that you see create in the database cannot be used directly. I changed the password, took the hash using BCrypt, then edited the password in the table , and entered the new password.
This enabled me to get to the next step... but the project is still not complete and has some dependencied that are not build.. so nothing really happened after that. I am assuming it was the fdaResources folder fault!

Thanks,

Dhanya Sathyan

**Comment by FDA-MyStudies** [comment]
Hi @dhanyasathyan ,

Thank you for your interest in the MyStudies system. Apologies for the nearly year-long delay in responding. We only recently acquired additional funding to support open-source activities. In regards to your original question:

Default username: superadmin@gmail.com 
Default password: Password@1234

Password is encrypted and stored in database.  To change the password you need to do 'forgot password' or change password after application login.

If you are not able to login with these credentials, there is some issue in database connection.  Maybe the application is not connecting to proper database schema.  Look at the error in tomcat console.  Is  there any issue with connecting database or application is not deployed and running?  If so, post the error message, so we can help you out.

Regarding fdaResources, this is just simple java web application project.  Here we store all the application-related resources, like image files, which are uploaded through the application. This project will not cause any issue to run the WCP application. You just take this application and deploy in tomcat webapps folder and run as simple project.

**Comment by liujoshua** [comment]
I am also having trouble signing in with the provided credentials. No issue with database connector in the logs.

Only issue is this:

> web_1  | 2020-02-26 13:11:48,227  INFO [http-nio-8080-exec-4] (HibernateUtil.java:56) - INFO: HibernateUtil - getSessionFactory() :: Starts
web_1  | 2020-02-26 13:11:48,228 ERROR [http-nio-8080-exec-4] (HibernateUtil.java:68) - HibernateUtil - getSessionFactory() :: ERROR
web_1  | java.lang.NullPointerException
web_1  |        at java.io.FileInputStream.<init>(FileInputStream.java:130)
web_1  |        at java.io.FileInputStream.<init>(FileInputStream.java:93)
web_1  |        at com.hphc.mystudies.util.HibernateUtil.getSessionFactory(HibernateUtil.java:61)
web_1  |        at com.hphc.mystudies.dao.AppMetaDataDao.<init>(AppMetaDataDao.java:77)
web_1  |        at com.hphc.mystudies.integration.AppMetaDataOrchestration.<init>(AppMetaDataOrchestration.java:61)
web_1  |        at com.hphc.mystudies.service.StudyMetaDataService.<init>(StudyMetaDataService.java:90)
web_1  |        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
web_1  |        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
web_1  |        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
web_1  |        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

But this does not seem to produce errors in the logs

Here is the log output:

> web_1  | 2020-02-26 13:11:48,229  INFO [http-nio-8080-exec-4] (HibernateUtil.java:70) - INFO: HibernateUtil - getSessionFactory() :: Ends
web_1  | 2020-02-26 13:11:48,287  INFO [http-nio-8080-exec-4] (StudyMetaDataService.java:943) - INFO: StudyMetaDataService - ping() :: Starts
web_1  | 2020-02-26 13:11:48,287  INFO [http-nio-8080-exec-4] (StudyMetaDataService.java:945) - INFO: StudyMetaDataService - ping() :: Ends
web_1  | 2020-02-26 13:11:48,363  INFO [http-nio-8080-exec-4] (RestAuthenticationFilter.java:102) - INFO: RestAuthenticationFilter - doFilter() - Ends
web_1  | 2020-02-26 13:12:02,469  INFO [taskScheduler-1] (NotificationDAOImpl.java:220) - NotificationDAOImpl - getPushNotificationList - Starts
web_1  | 2020-02-26 13:12:02,720  INFO [taskScheduler-1] (NotificationDAOImpl.java:272) - NotificationDAOImpl - getPushNotificationList - Ends
web_1  | 2020-02-26 13:12:06,040  WARN [http-nio-8080-exec-6] (FdahpStudyDesignerUtil.java:327) - FdahpStudyDesignerUtil - getAppProperties() :: Properties Initialization
web_1  | 2020-02-26 13:12:06,059  INFO [http-nio-8080-exec-6] (LoginDAOImpl.java:214) - LoginDAOImpl - getValidUserByEmail() - Starts
web_1  | 2020-02-26 13:12:06,131  INFO [http-nio-8080-exec-6] (LoginDAOImpl.java:241) - LoginDAOImpl - getValidUserByEmail() - Ends
web_1  | 2020-02-26 13:12:06,131  INFO [http-nio-8080-exec-6] (AuditLogDAOImpl.java:78) - AuditLogDAOImpl - saveToAuditLog() - Starts
web_1  | 2020-02-26 13:12:06,288  INFO [http-nio-8080-exec-6] (AuditLogDAOImpl.java:118) - AuditLogDAOImpl - saveToAuditLog - Ends
web_1  | 2020-02-26 13:12:06,288  INFO [http-nio-8080-exec-6] (LoginDAOImpl.java:147) - LoginDAOImpl - getUserAttempts() - Starts
web_1  | 2020-02-26 13:12:06,316  INFO [http-nio-8080-exec-6] (LoginDAOImpl.java:164) - LoginDAOImpl - getUserAttempts() - Ends
web_1  | 2020-02-26 13:12:06,350  INFO [http-nio-8080-exec-6] (LoginDAOImpl.java:214) - LoginDAOImpl - getValidUserByEmail() - Starts
web_1  | 2020-02-26 13:12:06,371  INFO [http-nio-8080-exec-6] (LoginDAOImpl.java:241) - LoginDAOImpl - getValidUserByEmail() - Ends
web_1  | 2020-02-26 13:12:06,379  WARN [http-nio-8080-exec-7] (FdahpStudyDesignerUtil.java:327) - FdahpStudyDesignerUtil - getAppProperties() :: Properties Initialization
web_1  | 2020-02-26 13:12:06,381  WARN [http-nio-8080-exec-7] (FdahpStudyDesignerUtil.java:327) - FdahpStudyDesignerUtil - getAppProperties() :: Properties Initialization
web_1  | 2020-02-26 13:13:00,002  INFO [taskScheduler-1] (NotificationDAOImpl.java:220) - NotificationDAOImpl - getPushNotificationList - Starts
web_1  | 2020-02-26 13:13:00,081  INFO [taskScheduler-1] (NotificationDAOImpl.java:272) - NotificationDAOImpl - getPushNotificationList - Ends
web_1  | 2020-02-26 13:14:00,002  INFO [taskScheduler-1] (NotificationDAOImpl.java:220) - NotificationDAOImpl - getPushNotificationList - Starts
web_1  | 2020-02-26 13:14:00,082  INFO [taskScheduler-1] (NotificationDAOImpl.java:272) - NotificationDAOImpl - getPushNotificationList - Ends
web_1  | 2020-02-26 13:14:03,478  WARN [http-nio-8080-exec-10] (FdahpStudyDesignerUtil.java:327) - FdahpStudyDesignerUtil - getAppProperties() :: Properties Initialization
web_1  | 2020-02-26 13:14:03,485  INFO [http-nio-8080-exec-10] (LoginDAOImpl.java:214) - LoginDAOImpl - getValidUserByEmail() - Starts
web_1  | 2020-02-26 13:14:03,506  INFO [http-nio-8080-exec-10] (LoginDAOImpl.java:241) - LoginDAOImpl - getValidUserByEmail() - Ends
web_1  | 2020-02-26 13:14:03,506  INFO [http-nio-8080-exec-10] (AuditLogDAOImpl.java:78) - AuditLogDAOImpl - saveToAuditLog() - Starts
web_1  | 2020-02-26 13:14:03,591  INFO [http-nio-8080-exec-10] (AuditLogDAOImpl.java:118) - AuditLogDAOImpl - saveToAuditLog - Ends
web_1  | 2020-02-26 13:14:03,592  INFO [http-nio-8080-exec-10] (LoginDAOImpl.java:147) - LoginDAOImpl - getUserAttempts() - Starts
web_1  | 2020-02-26 13:14:03,610  INFO [http-nio-8080-exec-10] (LoginDAOImpl.java:164) - LoginDAOImpl - getUserAttempts() - Ends
web_1  | 2020-02-26 13:14:03,611  INFO [http-nio-8080-exec-10] (LoginDAOImpl.java:214) - LoginDAOImpl - getValidUserByEmail() - Starts
web_1  | 2020-02-26 13:14:03,632  INFO [http-nio-8080-exec-10] (LoginDAOImpl.java:241) - LoginDAOImpl - getValidUserByEmail() - Ends
web_1  | 2020-02-26 13:14:03,641  WARN [http-nio-8080-exec-1] (FdahpStudyDesignerUtil.java:327) - FdahpStudyDesignerUtil - getAppProperties() :: Properties Initialization
web_1  | 2020-02-26 13:14:03,646  WARN [http-nio-8080-exec-1] (FdahpStudyDesignerUtil.java:327) - FdahpStudyDesignerUtil - getAppProperties() :: Properties Initialization
