### ISSUE TITLE
add link to  May 2019 webinar to main readme

### ISSUE THREAD

**Issue by vojtechhuser** [PopMedNet-Team/Mobile-Application#19]
https://sbiaevents.com/mystudies/

https://sbiaevents.com/files2/MyStudies-Slides.pdf

**Comment by FDA-MyStudies** [comment]
@vojtechhuser  

Thank you for the suggestion. We would like to keep the github repository limited to developer/end user questions. However, we maintain those links as a resource to which we can direct interested parties once we start conversations outside of github.
