### ISSUE TITLE
Unable to schedule Questionnaires based on study enrollment as Anchor Date

### ISSUE THREAD

**Issue by benapra** [PopMedNet-Team/Mobile-Application#25]
The update mentions this new feature:
Ability to schedule study activities and resources based on study enrollment (or other WCP-configured date elements) as Anchor Date

Yet I can't see it on the StudyDesigner web app. Did anyone manage to use that feature?

Thanks a lot!

**Comment by FDA-MyStudies** [comment]
@benapra Are you still having this issue? The 2019.05 branch was updated in early June to correct this issue.
