### ISSUE TITLE
No "Mobile App Study" option in Labkey

### ISSUE THREAD

**Issue by seanthingee** [PopMedNet-Team/Mobile-Application#28]
I think I have everything compiled and installed correctly, but I must not. 

I'm at the point trying to create a study and setup enrollment tokens, section 7.2 of the Setup Instructions. It's light on details and directs you to the [Labkey documentation](https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/blob/2019.05/LabKey%20Documentation/Set%20Up%20%20_FDA%20Mobile%20App.htm). 

In that documentation under "Create a Subfolder" heading, it says to "Create a new folder of type Mobile App Study within the project." My installation doesn't have a "Mobile App Study" option. I'm assuming that selecting "Mobile App Study" will also unlock UI for the next steps for setting the Study ID and creating tokens since I don't see those options for a regular "Study".

Does anyone know how to fix this?

**Comment by aaronboss** [comment]
I'm not sure if this helps or not, but I did notice there is a folder in the project called mobileAppStudy-ResponseServer. It looks like readme has a few more instructions to get this built up.

[](https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/tree/2019.05/mobileAppStudy-ResponseServer)

**Comment by seanthingee** [comment]
@aaronboss Thanks so much for that, that was exactly what I needed to do. Frustrating that it seems to be skipped in the documentation.

**Comment by FDA-MyStudies** [comment]
Hi @seanthingee Glad you were able to find what you needed.  We are working on improving our documentation right now!  We realize it is not the most user-accessible.
