### ISSUE TITLE
License headers in JSP files are not in comments and spills into rendered HTML

### ISSUE THREAD

**Issue by gubikmic** [PopMedNet-Team/Mobile-Application#30]
This commit https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/commit/96b1bb3527c8c48b38bb338d3274af874646837a seems to have been intended to change the date in the copyright notice but it also broke the format and the notice is no longer contained in a comment and thus it spills into the rendered HTML.

Am I missing something? I'm wondering why nobody noticed this.

**Comment by seifscape** [comment]
I updated the license above each file with the commit before it was broken by replace the text with: 
``

**Comment by FDA-MyStudies** [comment]
@gubikmic ,
 @seifscape  is correct.

This will work file if you take the latest code; there was  some character issue while copying the copyright message from a word document. This issue has been fixed in last release 2019.10
