### ISSUE TITLE
java.io.FileNotFoundException: \usr\local\application.properties (The system cannot find the path specified)

### ISSUE THREAD

**Issue by kuttima** [PopMedNet-Team/Mobile-Application#32]
I am having the same issue mentioned here:
https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/issues/23
The problem seems to originate here:
(FdahpStudyDesignerUtil.java:341) - FdahpStudyDesignerUtil - getAppProperties() :: Properties Initialization

I am starting a new issue since my question in the old one might get unnoticed. Not able to proceed. Any help or suggestion is much appreciated.

**Comment by liujoshua** [comment]
I found a solution: https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/issues/23#issuecomment-591421100
