### ISSUE TITLE
'server error' when signing in or getting started

### ISSUE THREAD

**Issue by kuttima** [PopMedNet-Team/Mobile-Application#33]
I am able to see the initial page of the app. But, when I click get started or try to register and get to the landing page of the FDA MyStudies gateway page, the page that lists the studies, I get a 'server error' and the page keeps reloading (failed refresh token calls). 
I went through the logs and it looks like there is a 401 happening at the WCP. I have pasted the line from the log below:
"GET /fdahpStudyDesigner/studyList HTTP/1.1" 401 1034
Does anybody know why this is happening. The account I am using to log in has full rights on this folder. Why is the api from the registration server not able to get to this folder. Should I be doing something else. Any suggestions  please?

**Comment by FDA-MyStudies** [comment]
Thanks for your patience as we review the open issues.

This issue looks like Basic Authorization setup is not done, as a part to WCP and webservice deployment process, there are some setup processes to follow. Details can be found in setup document in section 2.2.3 and 4.5.3.

https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/blob/2019.10/FDAMyStudies_Release%202019.10_SetupInstructions_V1.0.pdf "
