### ISSUE TITLE
Interested in consulting to implement FDA MyStudies??

### ISSUE THREAD

**Issue by kuttima** [PopMedNet-Team/Mobile-Application#34]
Are you available for consulting? We are interested in implementing the FDA MyStudies project for our organization. We would like to bring aboard some one to help us do that. Please let us know at your earliest.

**Comment by FDA-MyStudies** [comment]
@kuttima 

Apologies for the delay in responding. We do have some limited capacity for consulting and assisting external organizations spin up the system. If you are still interested, feel free to email me directly - zachary_wyner@harvardpilgrim.org to set up some time to discuss how we can help.
