### ISSUE TITLE
authorizationResource.properties

### ISSUE THREAD

**Issue by seifscape** [PopMedNet-Team/Mobile-Application#37]
@PopMedNet-Team @FDA-MyStudies I have been able to successfully build everything, the only issue that is holding me back is where do I retrieve these values other than the bundle id for both Android and iOS. If you could provide that would help me actually finally see this up and running!

Thanks!

**Comment by FDA-MyStudies** [comment]
Hi @seifscape ,

BundleID and AppToken are security parameters, used to communicate between WCP-WS and other applications.

**Bundleid**

Bundleid is the package name of mobile application (Android or iOS).  Each WCP-WS communication occurs using bundleID.  This is configured in authorizationResource.properties in WCP-WS(Refer section 4.3.2 for IOS and section 5.4.1.d in the release document).

Steps to create BundleID:
- You have to take bundleID from mobile application (like application package name,i.e. com.fda.xxx) and add into authorizationResource.properties (configured as a part of WCP-WS setup process).
- Mobile webservice communication should be happened through bundleID, refer the below mobile code, class file for you reference.

https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/blob/2019.05/Android/app/src/main/java/com/harvard/fda/webserviceModule/apiHelper/HttpRequest.java

You have to modify this line of code highlighted to add your package details .

private static String basicAuth = AppConfig.PackageName + ":a7296a62-44e8-4a06-8d85-50bc861d6c64";

**AppToken**

We have to create the one AppToken for each WCP-WS communication.  With the current WCP-WS application, we need to create a AppToken for Android, iOS and Response server.  These 3 applications are communicated to WCP-WS. This is part of WCP-WS setup process.

Once AppToken(can be Base64 encoded value) is created add into authorizationResource.properties., all communication should be happened through this unique token. If any request is coming from other than these 3 applications, authentication will fail.

**Comment by LucaCerina** [comment]
Hello,
it's still unclear to me how the appToken is generated. Is it arbitrary like the applicationId? it is generated as unique UUID?

**Comment by LucaCerina** [comment]
It is also unclear what is the labkey bundleId from the documentation. I guess the appToken is the one set with a new Mobile App Study folder
