### ISSUE TITLE
[code quality] StudyInfoActivity.java - comments as version control

### ISSUE THREAD

**Issue by ilyash-b** [PopMedNet-Team/Mobile-Application#41]
https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/blob/5ba692e8fced1f1b476351d00cbe0b62c54e1533/Android/app/src/main/java/com/harvard/fda/studyAppModule/StudyInfoActivity.java#L239-L281

Note that things superficial as this one make one wonder about the overall code quality.

**Comment by FDA-MyStudies** [comment]
Thanks for the submission, sorry for the late reply.
We are currently working with our developers on building new features and improving the code quality. These recommendations will be addressed in our next release.
