### ISSUE TITLE
[code quality] Duplicate code all over - WTF?

### ISSUE THREAD

**Issue by ilyash-b** [PopMedNet-Team/Mobile-Application#45]
`Integer.parseInt(responseCode) >= 201 && Integer.parseInt(responseCode) < 300 && response.equalsIgnoreCase("")` and surrounding code - 22 matches in 18 files.

**Comment by FDA-MyStudies** [comment]
We are currently working with our developers on building new features and improving the code quality. This duplicate code will be addressed in our next release
