### ISSUE TITLE
ORKNavigationContainerView error 

### ISSUE THREAD

**Issue by doomlab** [PopMedNet-Team/Mobile-Application#47]
<img width="893" alt="image" src="https://user-images.githubusercontent.com/27783894/75127138-74e79b80-568b-11ea-884f-2f9aa77d0ab9.png">

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ORKNavigationContainerView", referenced from:
      objc-class-ref in EligibilityStepViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any idea how to fix this error? @FDA-MyStudies

**Comment by FDA-MyStudies** [comment]
Thanks for the submission.

We are currently working with our developers on building new XCode. This will be addressed in our next release.

For now, the you can try making below changes and it'll solve the issue:

1. Select & edit the scheme for the current Target.
2. For Run & Archive, change the Build configuration to Debug.
3. Delete the Derived data before building the project again.

Regards,
The FDA MyStudies Team
