### ISSUE TITLE
mobileAppStudy fails to build

### ISSUE THREAD

**Issue by LucaCerina** [PopMedNet-Team/Mobile-Application#53]
Hello,
I am having some troubles while building the response server. I get this error
```
C:\dev\labkey\trunk\server\optionalModules\mobileAppStudy\src\org\labkey\mobileappstudy\MobileAppStudyController.java:530: error: getSchema() in SelectRowsForm cannot override getSchema() in QueryForm
        public UserSchema getSchema()
                          ^
  overridden method is final
```

**Comment by karpatit** [comment]
Hello, 
I have the same problem. Tried also with ./gradlew deployApp and get the same error.

**Comment by alanhughes** [comment]
Which version of labkey are you folks using? We got this error (and a couple of others) in 20.3 but not in 19.2

**Comment by karpatit** [comment]
I used the development version 19.2 as stated in the instructions. The problem was related to the fact that I downloaded the Github modules without realizing they were version 20. When changed the branch of the modules to version 19.2 the compilation ended successfully.

**Comment by FDA-MyStudies** [comment]
We will be deploying the most recent code to a new repo for this project in the next few weeks and are also planning to greatly improve the build process for the app shortly after that. I'll keep this ticket open so I can include a link when we're ready to point you there.

My deepest apologies that we haven't properly responded to these issues before now.

Amanda from the MyStudies team.

**Comment by FDA-MyStudies** [comment]
We're hopeful that build issues are resolved in our latest code, located at the new repo linked here: https://github.com/FDA-MyStudies/FDA-My-Studies-Mobile-Application-System

Thanks!
Amanda from the MyStudies team
