### ISSUE TITLE
FdahpUserRegUtil fail to build due to missing notnoop dependency

### ISSUE THREAD

**Issue by LucaCerina** [PopMedNet-Team/Mobile-Application#54]
With the last version of LabKey both com.notnoop.apns.APNS and com.notnoop.apns.ApnsService fail to be resolved, and the entire build fails

**Comment by FDA-MyStudies** [comment]
We believe we've resolved this issue in our latest build, which will be available soon on our new repo. As such, I'm going to close this ticket.

- Amanda from the MyStudies team
