### ISSUE TITLE
please add a proper build process

### ISSUE THREAD

**Issue by LucaCerina** [PopMedNet-Team/Mobile-Application#55]
Hello,
after days of meddling with multiple versions of LabKey, failing gradle processes, JVM conflicts and others I ask you to include a proper build system in the next release, taking care of required version of all components and such.

It's incredible that an open source project like this does not have a reliable continuous integration build process and/or some binary releases that can be installed with minimal hassle. There is a lot of files that are manually edited and moved and that increases A LOT the risk of bugs and problems!

**Comment by FDA-MyStudies** [comment]
Just confirming that we're doing this in the near future. It will live in our new repo and we'll be making more improvements in the future. Thank you for this comment and we know we need to improve this!

Amanda from the MyStudies team
