### ISSUE TITLE
iOS App error in getting study list from WCP

### ISSUE THREAD

**Issue by hjsonghjsong** [PopMedNet-Team/Mobile-Application#59]
Hello. 

After I setup WCP, I created the study from WCP portal  (HTTP://localhost:8080/fdahpStudyDesigner) and launched it.
I build the iOS app, and ran it on iPhone simulator.

I clicked FDA MyStudes --> Home as in the attached file. It says no study is available. 
From the Xcode debug, I also found  HTTP://localhost:8080/fdahpStudyDesigner/studyList request is made. But it also said the requestname Failed.

On browser, I tried to connect HTTP://localhost:8080/fdahpStudyDesigner/studyList.  I got PageNotFound error. 
However, at HTTP://localhost:8080/fdahpStudyDesigner, I found my study is there as in the attached image. 

I wonder what is wrong. 
<img width="629" alt="Screen Shot 2020-07-01 at 9 03 35 PM" src="https://user-images.githubusercontent.com/17757289/86241898-b9a5b500-bbde-11ea-848a-d76b5f840996.png">
<img width="407" alt="Screen Shot 2020-07-01 at 9 03 41 PM" src="https://user-images.githubusercontent.com/17757289/86241921-c1fdf000-bbde-11ea-9a32-92927036c5d1.png">
<img width="477" alt="Screen Shot 2020-07-01 at 9 03 51 PM" src="https://user-images.githubusercontent.com/17757289/86241929-c4f8e080-bbde-11ea-8024-1ec5a0f6eb23.png">
![Screen Shot 2020-07-01 at 9 02 32 PM](https://user-images.githubusercontent.com/17757289/86241944-cd511b80-bbde-11ea-8346-6e59aa8fcb86.png)

**Comment by tushar-boston** [comment]
Hi,

Could you please verify `Allow Arbitrary Loads` & `Allow Arbitrary Loads in Web Content` is updated to true in [info.plist](https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/blob/2019.10/iOS/HPHC/HPHC/Info.plist) since you're trying to access over HTTP.

Also Add `Allows Local Networking` to YES under `App Transport Security Settings` if you're accessing a local server.

**Comment by FDA-MyStudies** [comment]
I'm going to close this issue due to inactivity.

- Amanda from the MyStudies team
