### ISSUE TITLE
Task 'dist' not found in project ':server:optionalModules:mobileAppStudy:distributions:fda'.

### ISSUE THREAD

**Issue by shooyin** [PopMedNet-Team/Mobile-Application#64]
Hi guys,

I'm in Section 6, trying to run a stand-alone Response Server. I'm running macOS Catalina with Java 14. 

At step 6, we're instructed to run:
./gradlew :server:optionalModules:mobileAppStudy:distributions:fda:dist

But I run into this error:
Task 'dist' not found in project ':server:optionalModules:mobileAppStudy:distributions:fda'.

Things I've Tried:
- svn checkout (https://svn.mgt.labkey.host/stedi/branches/release19.2 || https://svn.mgt.labkey.host/stedi/trunk) (labkey dir)
- Upgrading gradle to latest ver through gradle-wrapper.properties

**Comment by FDA-MyStudies** [comment]
We're hopeful that issues like this are resolved in our latest code, located at the new repo linked here: https://github.com/FDA-MyStudies/FDA-My-Studies-Mobile-Application-System

If you still experience issues, please open an issue on the new repo and we will work to troubleshoot it.

Thanks!
Amanda from the MyStudies team
