### ISSUE TITLE
Can someone tell about the base urls that need to put in Android configuration?

### ISSUE THREAD

**Issue by shbmgupta** [PopMedNet-Team/Mobile-Application#65]

**Comment by FDA-MyStudies** [comment]
@shub29shub Can you let me know if you still need this information? If so, I will track it down and follow up on the ticket.

Amanda from the MyStudies team

**Comment by FDA-MyStudies** [comment]
Closing this ticket for inactivity. As an FYI, we have posted updated code located at the new repo linked here: https://github.com/FDA-MyStudies/FDA-My-Studies-Mobile-Application-System

If you still experience issues, please open an issue on the new repo and we will work to troubleshoot it.

Thanks!
Amanda from the MyStudies team
