### ISSUE TITLE
Is there an OpenAPI or other documentation of the API for the registration server and the WCP server/

### ISSUE THREAD

**Issue by jamesagada** [PopMedNet-Team/Mobile-Application#68]

**Comment by FDA-MyStudies** [comment]
@jamesagada We are working on relaunching this app into a new GitHub repo with additional documentation to help in situations like this. I'm going to keep this ticket open until we're ready to share the link to the new repo and will be working no adding documentation about this type of thing.

Thanks!
Amanda from the MyStudies team

**Comment by FDA-MyStudies** [comment]
We have been working on documentation revisions as part of relaunching this code in a new repo linked here: https://github.com/FDA-MyStudies/FDA-My-Studies-Mobile-Application-System

If you still experience issues or have future questions, please open an issue on the new repo and we will work to troubleshoot it.

Thanks!
Amanda from the MyStudies team
