### ISSUE TITLE
UserReg-WS is failing to build

### ISSUE THREAD

**Issue by smunini** [PopMedNet-Team/Mobile-Application#70]
Getting this build error after copying UserReg-WS to labkeyHome/server/modules/UserReg-WS

Build file '/Users/[my username]/git/labkeyHome/server/modules/UserReg-WS/distributions/Registration/build.gradle' line: 38

A problem occurred evaluating project ':server:modules:UserReg-WS:distributions:Registration'.
> Could not create task ':server:modules:UserReg-WS:distributions:Registration:distribution'.
   > Could not create task of type 'ModuleDistribution'.
      > Cannot build non-open source distribution. Unable to find project with the plugin org.labkey.build.applyLicenses in :server:modules:UserReg-WS:distributions:Registration ancestors.

**Comment by FDA-MyStudies** [comment]
Hi @smunini,

I'm sorry you ran into this issue building the code! We're currently in the process of relaunching the most recent code for the MyStudies app in a brand new GitHub repo (link coming soon), with the goal of finalizing that launch in the next few weeks. I hope that this build issue is solved by the new code, but in the event that it isn't, we'll also be reviewing how to improve the build process and adding enhancements to make this easier.

I hope this information helps in the interim while we work to get our open source code up to date for future development.

Thank you!
Amanda from the MyStudies Team

**Comment by FDA-MyStudies** [comment]
As mentioned above, we hope that this issue is resolved in our latest code, located at the new repo linked here: https://github.com/FDA-MyStudies/FDA-My-Studies-Mobile-Application-System

If you still experience issues, please open an issue on the new repo and we will work to troubleshoot it.

Thanks!
Amanda from the MyStudies team
