### ISSUE TITLE
fdahpStudyDesigner build encoding issue

### ISSUE THREAD

**Issue by formanojhr** [PopMedNet-Team/Mobile-Application#9]
I noticed the the encoding for the build seems to be in UTF-8 but build failed with unrecognizable chars when trying to build in UTF-8. Once, I changed it to 

<encoding>ISO-8859-1</encoding>
it built successfully.  I think the pom might need a fix for the char encoding or the other way the source might need to be checked in UTF-8. The following updates were done to allow building:
<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<version>2.1.1</version>
				<configuration>
					<packagingExcludes>WEB-INF/web.xml,META-INF/context.xml,studylogo/,studypages/,studyResources/,questionnaire/</packagingExcludes>
					**<encoding>ISO-8859-1</encoding>**
					<webResources>
						<resource>
							<directory>${project.build.directory}/${project.build.finalName}/</directory>
						</resource>
					</webResources>
				</configuration>
			</plugin>
			
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<webXml>WEB-INF/web.xml</webXml>
					<source>1.7</source>
					<target>1.7</target>
					**<encoding>ISO-8859-1</encoding>>**
				</configuration>
			</plugin>
			<plugin>

**Comment by s37-robert** [comment]
I was able to get around this issue by adding one line to pom.xml:

https://github.com/PopMedNet-Team/FDA-My-Studies-Mobile-Application-System/pull/11

Is this the same thing you encountered?

**Comment by FDA-MyStudies** [comment]
Hi @formanojhr ,
Thank you for your interest in the MyStudies system.  Apologies for the year-long delay in responding.  We only recently acquired additional funding to support open-source activities.   In regards to your original question:
 
This will be resolved by adding below link in pom.xml file

<properties>
           <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
</properties>

By adding this line in pom.xml will take care the encoding the source code. If your IDE (Eclipse or other) has default set to UTF-8, this issue won't occur.

Our latest release 2019.10 is addressed this issue, it works fine if you take the latest code from Gibhub.
